### ISSUE TITLE
When attempting to export a structure from the Content Studio widget, i get a 404 error

### ISSUE THREAD

**Issue by sigdestad** [GlennRicaud/data-toolbox-app#114]
Using 3.0.0 version live on enonic market at the time of writing.

See screenshot below.
<img width="842" alt="Screenshot 2019-04-16 at 18 09 40" src="https://user-images.githubusercontent.com/482228/56226100-e2da3400-6072-11e9-95d5-c7eac49c7f9a.png">

**Comment by GlennRicaud** [comment]
Thanks for reporting :)
Fixed in https://github.com/GlennRicaud/data-toolbox-app/issues/110 (7.0.0)
Closing this issue
