### ISSUE TITLE
Parent link

### ISSUE THREAD

**Issue by runarmyklebust** [GlennRicaud/data-toolbox-app#19]
Suggestions:

* Add parent link on top in list
* Add "hasChild" indication to items
* If no children, show info on click

**Comment by GlennRicaud** [comment]
To display an empty list of children is still necessary because of the 'import' functionality. I am also a bit worried that the user gets too confused (the interface is already a bit confusing :S ). We can discuss it.

The parent link is a good idea thanks :+1:
