### ISSUE TITLE
Slow loading of exports if many exports 

### ISSUE THREAD

**Issue by runarmyklebust** [GlennRicaud/data-toolbox-app#2]
Seems to take a while when you have alot of (big?) exports in repo

**Comment by rcd-systems** [comment]
Yes. It is because of the size computation of folder.
I guess I could try to cache the information

**Comment by GlennRicaud** [comment]
I could have a service that computes the dumps size on initialisation and cache the result by <dumpname> + <modifiedTime> (Then updates the caches for the dumps created/deleted/modified).

Or I could  simply delete the functionality. It seems to be a lot of time consumption for an information non essential.

What do you think @runarmyklebust ?

**Comment by GlennRicaud** [comment]
Fixed in 1.0.0
