### ISSUE TITLE
Stream directly to zip/tar

### ISSUE THREAD

**Issue by diegopasten** [GlennRicaud/data-toolbox-app#2]
Would be nice if the dump could be made directly to an archive.

Context.

For a full dump disk space needs to be three times the size of repo. This is because total disk requires space for: repo + dump + compressed dump.

Even if the disk problem is solved by mounting data-folder as a separate volume, there is still a time issue because of many steps.

Maybe this is an XP issue.

**Comment by GlennRicaud** [comment]
I agree with you. Having the export and dump already archived would be so much better. Faster and taking less space. Actually parts of the dump (>= 6.11) are already archived.
But yes this is an XP issue.

Closing this issue
