### ISSUE TITLE
Support `archive` parameter of dump API 

### ISSUE THREAD

**Issue by alansemenov** [GlennRicaud/data-toolbox-app#21]
Hi @GlennRicaud!

In XP 7.3 we introduced `archive` parameter for dump [create](https://developer.enonic.com/docs/xp/stable/runtime/management#create_2) and [load](https://developer.enonic.com/docs/xp/stable/runtime/management#load) API to enable creating/load zipped dumps.

Would be great if you added this option to Data Toolbox (or always pass "archive" to by default always zip/load from zip).

**Comment by GlennRicaud** [comment]
Done in https://github.com/GlennRicaud/data-toolbox-app/issues/22
Will be available in DT v5.0.0

**Comment by GlennRicaud** [comment]
@alansemenov:

Please restore my user for me to be able to manage the app on the market

If you are unsure about what rights to give me, I would need at least the following:
- Roles: system.admin.login, cms.cm.app
- Full access on content tree: /enonic-market/vendors/glenn-ricaud (Maybe a different path today)

**Comment by alansemenov** [comment]
@GlennRicaud it's restored. sent you details on Slack (in the XP community workspace)

**Comment by GlennRicaud** [comment]
Perfect. Thanks Alan!

**Comment by GlennRicaud** [comment]
Why were my rights removed?
