### ISSUE TITLE
Archiving of dump takes forever

### ISSUE THREAD

**Issue by poi33** [GlennRicaud/data-toolbox-app#23]
XP 7.4.0 
App: 5.0.0

After creating a system dump downloading the selected system dump takes does not archive it. 
Tried to do this on two different servers and it seems like it taes 45min + or silently failed at some point
No server log message, and no console message that i could find.

**Comment by GlennRicaud** [comment]
As mentioned in side discussion, I do not manage to reproduce this behaviour or at least I do not see any degradation of performance compared to previous versions.
Closing this issue for now
