### ISSUE TITLE
Links point to old documentation

### ISSUE THREAD

**Issue by nerdkid93** [GlennRicaud/data-toolbox-app#28]
The documentation links within your `displayHelp` dialogs all link to http://xp.readthedocs.io/en/6.10 or http://xp.readthedocs.io/en/6.11, which you no longer support as of (v3.0.0)[https://github.com/GlennRicaud/data-toolbox-app/tree/dev#releases-and-compatibility].

**Comment by GlennRicaud** [comment]
Yes, thank you for reporting it.

The reason was that at the release of v3.0.0 the new documentation (i.e. https://developer.enonic.com/docs/xp/stable) was still being written (this has been solved since).
I will found the equivalents in the new documentation and update the links :+1:

**Comment by GlennRicaud** [comment]
Fixed in Data Toolbox v5.0.3
