### ISSUE TITLE
Add support for filters in query

### ISSUE THREAD

**Issue by jonaslepsoy** [GlennRicaud/data-toolbox-app#44]
The search function in Data Toolbox is great for testing different queries quickly.

However, we would also like to be able to do [filters](https://developer.enonic.com/docs/xp/stable/storage/filters).

**Comment by GlennRicaud** [comment]
Good point. I will focus on this next.

**Comment by GlennRicaud** [comment]
Implemented in version 5.0.11. This should be available in the Enonic Market soon.
Meanwhile I also list direct download links on the README page: https://github.com/GlennRicaud/data-toolbox-app#releases-and-compatibility
