### ISSUE TITLE
Bintray is being sunsetted on May 1, 2021

### ISSUE THREAD

**Issue by nerdkid93** [GlennRicaud/data-toolbox-app#46]
Today, Bintray had a scheduled brown-out to notify users of a impending deprecation of the bintray service: 
![Screenshot from 2021-04-12 14-57-52](https://user-images.githubusercontent.com/6289786/114446693-85184e00-9b9f-11eb-91ba-02845f914401.png)

See these links for more details: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ and https://status.bintray.com/

**Comment by nerdkid93** [comment]
Upon further inspection, it appears that the Enonic Market is already using [rcdsystems.jfrog.io](https://rcdsystems.jfrog.io/artifactory/maven-public/systems/rcd/enonic/datatoolbox/) so maybe just the download links in [README.md](../tree/master/README.md#releases-and-compatibility) need to be updated? I'll submit a PR for that change

**Comment by GlennRicaud** [comment]
Thank for the notification 👍 And yes I already migrated it 2 weeks ago to `jfrog.io`
But I forgot to update the README links. Thanks for the PR. Merged now.
