### ISSUE TITLE
Would it be possible to see the actual analyzed index values

### ISSUE THREAD

**Issue by ComLock** [GlennRicaud/data-toolbox-app#57]
For example for stemmed fields?

I input "billig" and I would like to see that the stem is "bil".

This would be helpful while debugging search results...

This would be applicable for other types of indexes aswell. For example "ngram"

**Comment by GlennRicaud** [comment]
I will check what is possible this week end

**Comment by GlennRicaud** [comment]
Implemented. And will be available in DT 5.0.16

<img width="1069" alt="Screen Shot 2021-09-12 at 17 00 05" src="https://user-images.githubusercontent.com/12030113/132992592-1a1b7497-018b-4124-be1d-e7c03ddf01dc.png">
<img width="1067" alt="Screen Shot 2021-09-12 at 16 59 50" src="https://user-images.githubusercontent.com/12030113/132992594-598ec4d2-eebc-4042-b7c5-8406c9b2a05e.png">
<img width="1072" alt="Screen Shot 2021-09-12 at 16 59 33" src="https://user-images.githubusercontent.com/12030113/132992597-f373b958-4dfa-42c3-916c-e33f9b01f94f.png">

**Comment by ComLock** [comment]
Cool.
