### ISSUE TITLE
Select which fields are visible in the node list page

### ISSUE THREAD

**Issue by ComLock** [GlennRicaud/data-toolbox-app#59]
On the content layer we know that the modifiedTime field exist.
On the node layer such a field might have a different path.

For example in app-explorer I have it under document_metadata.modifiedTime.

It would be very nice if I could open a modal dialog to select or input some fields I would like to see in the nodes list page.

Perhaps even click column header to sort on that field.

**Comment by GlennRicaud** [comment]
Good idea :+1:
Will work on that next

**Comment by GlennRicaud** [comment]
Will be released with DT 5.0.18
