### ISSUE TITLE
Display fields visuals break

### ISSUE THREAD

**Issue by poi33** [GlennRicaud/data-toolbox-app#60]
![image](https://user-images.githubusercontent.com/3340349/141770177-802adae5-ffa8-4cc4-9df4-f6c2cf0edb9f.png)

* Header does not break word (`word-break: break` css?)
* Content goes outside its table cell. (Remove fixed height, or hide the overflow)
* Objects or nested values are displayed as [object Object]

**Comment by GlennRicaud** [comment]
Thanks Persijn,
I will fix that

**Comment by GlennRicaud** [comment]
Will be available in DT 5.0.25
