### ISSUE TITLE
Remove admin rest dependency 

### ISSUE THREAD

**Issue by sigdestad** [GlennRicaud/data-toolbox-app#63]
This might be a bug in XP 7.8-B, but it would be great if you took a look?

**Comment by GlennRicaud** [comment]
I installed and run Enonic XP 7.8.0-B1+Content Studio and I am getting 404 already there (cf. screenshot).
There is a problem with the distro and in particular the /admin/rest API
Reproduced after restart

I see the following logs at the end of the startup. Meaning that this happen after the applications have started:

> 2021-11-23 18:23:05,704 INFO  o.jboss.resteasy.resteasy_jaxrs.i18n - RESTEASY002225: Deploying javax.ws.rs.core.Application: class com.enonic.xp.jaxrs.impl.JaxRsServlet$JaxRsApplication
2021-11-23 18:23:05,705 INFO  o.jboss.resteasy.resteasy_jaxrs.i18n - RESTEASY002215: Adding singleton provider com.enonic.xp.jaxrs.impl.CommonFeature from Application class com.enonic.xp.jaxrs.impl.JaxRsServlet$JaxRsApplication
2021-11-23 18:23:05,706 INFO  o.jboss.resteasy.resteasy_jaxrs.i18n - RESTEASY002220: Adding singleton resource com.enonic.xp.admin.impl.rest.resource.status.StatusResource from Application class com.enonic.xp.jaxrs.impl.JaxRsServlet$JaxRsApplication
2021-11-23 18:23:05,706 INFO  o.jboss.resteasy.resteasy_jaxrs.i18n - RESTEASY002220: Adding singleton resource com.enonic.xp.admin.impl.rest.resource.auth.AuthResource from Application class com.enonic.xp.jaxrs.impl.JaxRsServlet$JaxRsApplication

**Comment by GlennRicaud** [comment]
<img width="1438" alt="Screen Shot 2021-11-23 at 18 23 08" src="https://user-images.githubusercontent.com/12030113/143073895-215771df-11e6-46b5-bfc5-ebbbfae4057b.png">

**Comment by GlennRicaud** [comment]
Update: It seems a lot of endpoint have been moved out of the runtime:
In 7.7: https://github.com/enonic/xp/tree/7.7/modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource
In 7.8.0.B1: https://github.com/enonic/xp/tree/v7.8.0-B1/modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource

That is a breaking change for ContentStudio (and also DataToolbox, that is reusing 1 existing endpoint even though it should not)

**Comment by GlennRicaud** [comment]
Not sure what is the gain by having `/admin/rest/tasks` duplicated in each XP app.

I will reimplement it in DT and release a new version of DT this week

**Comment by sigdestad** [comment]
Yes, we have removed all undocumented API, and out them into respective apps. CS4 fixes content studio

**Comment by GlennRicaud** [comment]
Fixed. Will be released in DT v5.0.20

**Comment by sigdestad** [comment]
Killer, is it 7.7 compatible as well?

**Comment by GlennRicaud** [comment]
Yes. Compatible with >=7.3 (So they can already update today).

I already sent the following information to Persijn:
```
- 5.0.20 (Nov 26th 2021)
  - Adaptation: Remove admin rest API dependency (Required by Enonic XP 7.8)
  - Compatibility:7.3.0
```
