### ISSUE TITLE
Create node function

### ISSUE THREAD

**Issue by rymsha** [GlennRicaud/data-toolbox-app#66]
It should be possible to create node inside the repository 

Given the branch and repository and a node selected
- (+) button should appear (next to import/export buttons)
- click on (+) button should ask for node name in the dialog 
- when dialogs OK button is pressed new node should be created with the provided name

node shoud created in selected repository, branch and parent node

https://developer.enonic.com/docs/xp/stable/api/lib-node#create

**Comment by GlennRicaud** [comment]
Will be available in DT v5.0.23
