### ISSUE TITLE
Artifactory site appears to be down

### ISSUE THREAD

**Issue by bcb37** [GlennRicaud/data-toolbox-app#67]
I've tried to install/download the built jars for this app, but am getting 502 from the host.
(e.g. https://rcdsystems.jfrog.io/artifactory/maven-public/systems/rcd/enonic/datatoolbox/5.0.19/datatoolbox-5.0.19.jar )

**Comment by GlennRicaud** [comment]
Thank you for notifying me. There seems to be a technical problem at JFrog.
I have contacted them.

If there is no fix soon I will find an alternative way to distribute them

**Comment by GlennRicaud** [comment]
I have made a Github release for the latest version v5.0.23 (compatible from Enonic XP 7.3): https://github.com/GlennRicaud/data-toolbox-app/releases/tag/v5.0.23

**Comment by GlennRicaud** [comment]
JFrog has apparently fixed their issue.
But good experience. In the future I will release on both platforms for redundancy.
Again thanks for the warning
