### ISSUE TITLE
Get rid of inline Javascript in the widget template

### ISSUE THREAD

**Issue by alansemenov** [GlennRicaud/data-toolbox-app#69]
Hi Glenn,

We are enforcing Content Security Policy in Content Studio, which means that inline Javascript will stop working in widgets after the upcoming 4.1.0 release. [This script](https://github.com/GlennRicaud/data-toolbox-base/blob/master/src/main/resources/admin/widgets/export/export.html#L7) has to be replaced.

Suggested fix:
1. Implement a service that returns required config object ([example](https://github.com/enonic/app-contentstudio-plus/blob/master/src/main/resources/services/config/config.js))

2. Pass url of the service as a data attribute to the client-side JS asset ([example](https://github.com/enonic/app-contentstudio-plus/blob/master/src/main/resources/admin/widgets/archive/archive.html#L2))

3. Inside the JS asset, get config service url from the data attribute and fetch config from the service ([example](https://github.com/enonic/app-contentstudio-plus/blob/master/src/main/resources/assets/js/main.ts#L143-L151)). In this last example we use lib-admin-ui to fetch the config, but you can use simple [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).

**Comment by GlennRicaud** [comment]
Hei Alan,

Thanks for the heads-up. I will do that tomorrow :+1:

**Comment by GlennRicaud** [comment]
Fixed in DT 5.0.24
