### ISSUE TITLE
The filter field is blanked out when paginating

### ISSUE THREAD

**Issue by anton-lilleby** [GlennRicaud/data-toolbox-app#70]
Data tooblox 5.0.24

An attempt on clicking next page will blank out the filter field. It would be nice if the field was not lost when paginating through nodes.

<img width="1196" alt="Screenshot 2022-07-01 at 11 14 28" src="https://user-images.githubusercontent.com/77336935/176866137-78a87944-0b1d-456c-b3fb-3c817f067c83.png">

<img width="348" alt="Screenshot 2022-07-01 at 11 16 27" src="https://user-images.githubusercontent.com/77336935/176865358-339ea378-6ce6-4859-a915-73d9c52b25fc.png">

**Comment by GlennRicaud** [comment]
Thanks for reporting the issue @anton-lilleby. I will fix it.

**Comment by GlennRicaud** [comment]
Fixed in DT 5.0.25
