### ISSUE TITLE
Support Emojis in JSON view 

### ISSUE THREAD

**Issue by rymsha** [GlennRicaud/data-toolbox-app#71]
Data Toolbox fails to render Emojis correctly in JSON view
![image](https://user-images.githubusercontent.com/2891483/183851872-4ca6d1c0-575c-4e17-b8d7-906543715a25.png)
![image](https://user-images.githubusercontent.com/2891483/183851959-906cb05a-0625-4efa-b374-9fb2c2b80fa2.png)

**Comment by GlennRicaud** [comment]
Thanks @rymsha
I will fix that

**Comment by GlennRicaud** [comment]
Released with 5.0.28
