### ISSUE TITLE
Feature request: Check available space on disk and warn administrator before creating a big dump/export

### ISSUE THREAD

**Issue by jonaslepsoy** [GlennRicaud/data-toolbox-app#73]
Dumps and exports can get pretty big for some sites. The create dump/export functionality should advise the administrator of the possibility of low disk space before creating a big dump/export.

Ideally, the widget and/or admin app should also display some warning message if disk space is running low.

**Comment by GlennRicaud** [comment]
Good ideas @jonaslepsoy  :+1:
I will work on this for the next version

**Comment by GlennRicaud** [comment]
Hei @jonaslepsoy,

As the prediction of the final size of a dump/export can be too time consuming, I ended up:
- Displaying the used/available space in the dump/export creation dialog.
- Adding a view displaying the used/available space for all sub folders of XP Home (as these are sometimes mounted differently).

The changes will be available in v5.0.26

Below are some screenshots, please give me some feedback if you think something should have been done differently.


<img width="297" alt="Screenshot 2023-04-06 at 18 40 42" src="https://user-images.githubusercontent.com/12030113/230442764-3ebd9cd3-99e9-400c-a703-070917c3e3ab.png">

<img width="494" alt="Screenshot 2023-04-06 at 18 41 08" src="https://user-images.githubusercontent.com/12030113/230442776-d7677f6a-df72-41e8-83b6-1bb96ff55fd6.png">
