### ISSUE TITLE
Archive restore feature

### ISSUE THREAD

**Issue by sigdestad** [GlennRicaud/data-toolbox-app#74]
With newer XP's - there is a branch in content repos i.e. com.enonic.cms.myrepo/draft/archive. Nodes placed in this location may be "restored" back into the /content structure using the new restore() function in the content API.

Can you add support for clicking a "restore" button when user selects an item withibn the draft/archive path of a CMS repo?

**Comment by GlennRicaud** [comment]
Will work on this next.

Note to self: Move this feature when https://github.com/GlennRicaud/data-toolbox-app/issues/78 is done

**Comment by GlennRicaud** [comment]
I started to work on a new view that uses the content lib instead of the node lib. So a view more specific to contents. I will add the restore button there. To be released in DT 5.0.32

**Comment by GlennRicaud** [comment]
Implemented in the Content View in DT 5.1.0
