### ISSUE TITLE
Don't use Nashorn classes directly

### ISSUE THREAD

**Issue by rymsha** [GlennRicaud/data-toolbox-app#77]
XP 7.13 Uses Java 17 that does not have `jdk.nashorn.api.scripting` classes anymore.

XP 7.13  [Upgrade notes](https://developer.enonic.com/docs/xp/stable/release/upgrade#v7_13_notes) suggest to migrate to XP’s Javascript API instead of using Nashorn directly.

> Usage of Java 11 Nashorn engine is now deprecated and will be removed in future XP versions. Currently warning is issued for each usage: Class x.y.Z uses unsupported jdk.nashorn. Application may stop working in future XP versions. Applications must not use Nashorn engine directly, but instead use XP’s Javascript API.

Note: Often it is possible to use Map instead of JSObject

**Comment by GlennRicaud** [comment]
Thank you for reporting it 👍 .
I will remove the usage of the jdk.nashorn.api.scripting

**Comment by GlennRicaud** [comment]
Released with 5.0.27

**Comment by alansemenov** [comment]
@GlennRicaud did you stop tagging releases? the last two releases are missing [here](https://github.com/GlennRicaud/data-toolbox-app/releases)
