### ISSUE TITLE
How to add nested field to CSV report in Data Toolbox Node Search?

### ISSUE THREAD

**Issue by johann1301s** [GlennRicaud/data-toolbox-app#80]
I would like to add a nested field to a CSV report inside Data Toolbox Node Search.

I added an image to clearify.

<img width="331" alt="Skjermbilde 2023-10-18 kl  13 41 52" src="https://github.com/GlennRicaud/data-toolbox-app/assets/25029220/a9a704cc-e062-47c9-af54-8e1d75592ed8">

If I just write `_id,_path,data`, it works fine, but if I try to select a nested field, it fails.

Is it possible to add nested fields to CSV reports?

**Comment by GlennRicaud** [comment]
Thank you for creating the issue and no it is not possible currently.
I will work on this next .
To be released in DT 5.1.1

**Comment by GlennRicaud** [comment]
Released as part of DT 5.1.1
The export of fields is now as TSV
