### ISSUE TITLE
Missing a progress indicator when uploading large exports (and possibly dumps) 

### ISSUE THREAD

**Issue by sigdestad** [GlennRicaud/data-toolbox-app#81]
It would be nice to have this, as it is currently impossible to know progress.
Maybe use similar approach as when uploading apps and media in Content Studio.

**Comment by GlennRicaud** [comment]
Good point. I will look at it this weekend.

**Comment by GlennRicaud** [comment]
Do you have some place in the code of Content Studio and Core to look as what was done and check if I can reuse something

**Comment by sigdestad** [comment]
I was thinking about media uploads. Click new content and drag in some files. Also, the same when uploading applications.

**Comment by GlennRicaud** [comment]
Ah yes I got it now. I will mimic that then.
I am on holidays for a week starting from Thursday, I will have plenty of time to work on this then.

**Comment by sigdestad** [comment]
Sweet. Marry X-mas Glenn 🎄

**Comment by GlennRicaud** [comment]
Progress indicator now present for both export and dump upload (both in the tool and the widget)
Included in DT 5.0.31

<img width="357" alt="Screenshot 2023-12-27 at 13 27 16" src="https://github.com/GlennRicaud/data-toolbox-app/assets/12030113/96bfd594-9da4-4e23-b6c4-b2d8b1f13cc9">
