### ISSUE TITLE
In XP8 we will remove "setActiveVersion()" from all API's 

### ISSUE THREAD

**Issue by sigdestad** [GlennRicaud/data-toolbox-app#83]
The reason is that we want all changes to be traceable and incremental.
SetActiveVersion needs to be removed from Data Toolbox, and if possible it can be removed before the release of XP8

**Comment by GlennRicaud** [comment]
I will work on it and release a new version on Thursday

**Comment by GlennRicaud** [comment]
Released in DT 5.1.2
