### ISSUE TITLE
Better information related to snapshot restore

### ISSUE THREAD

**Issue by sigdestad** [GlennRicaud/data-toolbox-app#84]
When a user selects, and clicks restore on a snapshot, XP may end up in a bad state based on background jobs still running. As such we need a "confirm dialog" that informs the user about the consequenses of restoring a snapshot.

Things to include in dialog:

* Will reset entire XP data to "snapshot time"
* Recommend running a snapshot before continuing
* Warn that a manual restart of XP is required after completion

Once the restore has completed, if possible show a big white screen saying - "Snapshot restored successfully. Please restart XP"

**Comment by sigdestad** [comment]
NOTE: If it does not already exist, a similar warning should be issued on "load of dump"

**Comment by GlennRicaud** [comment]
Released on DT 5.1.3
