### ISSUE TITLE
Better error report logging

### ISSUE THREAD

**Issue by sigdestad** [GlennRicaud/data-toolbox-app#85]
On rare occations (probably due to some inconsistency in node repo) performing a search with data toolbox will produce an error "Cannot get property "_id" of null" in the UI.

In the log, the error looks like this:

`(/lib/util.js) Error while querying nodes: Cannot get property "_id" of null`

It would be very helpful if the log could contain the actual ID of the node it is trying to load.

**Comment by GlennRicaud** [comment]
I will update with more info 👍
