### ISSUE TITLE
Dumps incompatible cross env. Win/OSX

### ISSUE THREAD

**Issue by edwardgronroos** [GlennRicaud/data-toolbox-app#9]
When downloading a dump created on a server running windows and unzipping it on OSX the paths are #!/!$/"()#!" and instead of folders the files get the full path name instead.

![image](https://cloud.githubusercontent.com/assets/254408/22691707/ff5cb370-ed3b-11e6-8ccc-33d663599107.png)

... while doing the same from my own server running on OSX and downloading I get the expected folder structure in the dump.

![image](https://cloud.githubusercontent.com/assets/254408/22691764/3e7c2504-ed3c-11e6-9498-c8a8bce95ba3.png)

When my colleague running windows localy extracts the same .zip file he gets the correct directories. Probably just an issue with the file separator.

**Comment by edwardgronroos** [comment]
@GlennRicaud any update here?
I would try it out some more an perhaps create a PR but the build wont work.
The build can't seem to find the `systems.rcd.fwk.core:rcd-fwk-core:7.0.1` ...

**Comment by GlennRicaud** [comment]
Sorry, I did not notice your issue untill now.
I will fix the build tonight and tell you when done

**Comment by GlennRicaud** [comment]
Hi. So I added the missing repository, it should download the 3 missing libs now.
It also uses lessc (called a comand line for the moment, so if it is not you must install less: npm install -g less).

But so about the problem. The zipping and unzipping is done in: https://github.com/rcd-systems/fwk-core/blob/master/src/main/java/systems/rcd/fwk/core/util/zip/impl/RcdSimpleZipService.java

I have not much time this evening. But if you can wait until Monday, I will fix the problem of cross-platform zip this week-end and release a new version on Monday morning.

**Comment by GlennRicaud** [comment]
Done.

Should be corrected in
1.0.6 (For Enonic  >=6.8)
1.1.1 (For Enonic  >=6.9. Include also unrelated new features).

I will update the market tomorrow.
But you can already download the jars at the following URLs:
https://dl.bintray.com/rcd-systems/rcd-repo/systems/rcd/enonic/datatoolbox/1.0.6/datatoolbox-1.0.6.jar
https://dl.bintray.com/rcd-systems/rcd-repo/systems/rcd/enonic/datatoolbox/1.1.1/datatoolbox-1.1.1.jar

**Comment by edwardgronroos** [comment]
Thanks!
